src/Pear.Web.Entry/Areas/Admin/Controllers/DepartmentController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;


namespace Pear.Web.Entry.Areas.Admin.Controllers
{

    /// <summary>
    /// 部门-后台控制器
    /// </summary>
    [Area("Admin")]
    [Route("Admin/[controller]/[action]")]
    [AppAuthorize]
    public class DepartmentController : Controller
    {
        /// <summary>
        /// 部门管理主视图
        /// </summary>
        /// <returns></returns>
        [SecurityDefine("admin.usercenter.dept:view")]
        public IActionResult Index()
        {
            return View();
        }


        /// <summary>
        /// 权限菜单新增-视图
        /// </summary>
        /// <returns></returns>
        [SecurityDefine("admin.usercenter.dept:add")]
        public IActionResult Add()
        {
            return View();
        }

        /// <summary>
        /// 权限菜单编辑-视图
        /// </summary>
        /// <returns></returns>
        [SecurityDefine("admin.usercenter.dept:edit")]
        public IActionResult Edit()
        {
            return View();
        }
    }
}

src/Pear.Web.Entry/Areas/Admin/Views/Department/Add.cshtml
@using Pear.Web.Core
@inherits PearRazorPage<object>
@{ Layout = "~/Views/Shared/_Layout.cshtml"; }
@{ ViewData["Title"] = "部门新增";}
@section header
{

}
<form class="layui-form" action="">
    <div class="mainBox">
        <div class="main-container">
            <div class="main-container">

                <div class="layui-form-item">
                    <label class="layui-form-label">上级部门</label>
                    <div class="layui-input-block">
                        <ul id="ParentDepartment" class="dtree" data-id="null"></ul>
                    </div>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label">名称</label>
                    <div class="layui-input-block">
                        <input type="text" name="name" lay-verify="name" autocomplete="off" placeholder="请输入名称" class="layui-input" />
                    </div>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label">图标</label>
                    <div class="layui-input-block">
                        <input type="text"  name="icon" id="icon" lay-verify="icon" autocomplete="off" placeholder="请输入图标" class="layui-input" />
                    </div>
                </div>


                <div class="layui-form-item">
                    <label class="layui-form-label">电话号码</label>
                    <div class="layui-input-block">
                        <input type="text" name="telephone" autocomplete="off" placeholder="请输入电话号码" class="layui-input" />
                    </div>
                </div>

                <div class="layui-form-item">
                    <label class="layui-form-label">传真号码</label>
                    <div class="layui-input-block">
                        <input type="text" name="fax" lay-verify="authorize" autocomplete="off" placeholder="请输入传真号码" class="layui-input" />
                    </div>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label">邮箱</label>
                    <div class="layui-input-block">
                        <input type="text" name="email" lay-verify="email" autocomplete="off" placeholder="请输入邮箱" class="layui-input" />
                    </div>
                </div>



                <div class="layui-form-item">
                    <label class="layui-form-label">显示排序</label>
                    <div class="layui-input-block">
                        <input type="text" name="sequence" lay-verify="sequence" autocomplete="off" placeholder="请输入排序号码" class="layui-input" value="1" />
                    </div>
                </div>

                <div class="layui-form-item">
                    <label class="layui-form-label">状态</label>
                    <div class="layui-input-block">
                        <input type="checkbox" name="enabled" value="true" lay-skin="switch" lay-text="启用|禁用" lay-filter="enabled" checked />
                    </div>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label">备注</label>
                    <div class="layui-input-block">
                        <textarea type="text" name="remark" lay-verify="remark" autocomplete="off" placeholder="请输入备注" class="layui-input layui-textarea"></textarea>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="bottom">
        <div class="button-container">
            <button type="submit" class="layui-btn layui-btn-normal layui-btn-sm" lay-submit="" lay-filter="department-save">
                <i class="layui-icon layui-icon-ok"></i>
                提交
            </button>
            <button type="reset" class="layui-btn layui-btn-primary layui-btn-sm">
                <i class="layui-icon layui-icon-refresh"></i>
                重置
            </button>
        </div>
    </div>
</form>
@section footer
{
    <script>
        layui.use(['form', 'jquery', 'http', 'popup', 'dtree', 'iconPicker'], function () {
            let form = layui.form;
            let $ = layui.jquery;
            let http = layui.http;
            let popup = layui.popup;
            let dtree = layui.dtree;
            let iconPicker = layui.iconPicker;

            


            dtree.renderSelect({
                elem: "#ParentDepartment",
                initLevel: "3",
                method: 'get',
                url: "/api/department/all",
                dataStyle: "layuiStyle",
                dataFormat: "list",
                accordion: true,
                line:true,
                response: {
                    statusName: "statusCode", //返回标识（必填）
                    statusCode: 200, //返回码（必填）
                    title:"name",
                }
            });

            iconPicker.render({
                elem: '#icon',
                type: 'fontClass',
                page: false
            });

            form.on('submit(department-save)', function (data) {

                data.field.parentId = data.field.ParentDepartment_select_nodeId || null;

                if (data.field.enabled == "true") {
                    data.field.enabled = true;
                } else {
                    data.field.enabled = false;
                }

                http.post('/api/department/add', JSON.stringify(data.field)).then((result) => {
                    if (result.succeeded) {
                        popup.success("保存成功", function () {
                            parent.layer.close(parent.layer.getFrameIndex(window.name));//关闭当前页
                            parent.refresh();
                        });
                    } else {
                        popup.failure("保存失败");
                    }
                });
                return false;
            });
        })
    </script>
}

src/Pear.Web.Entry/Areas/Admin/Views/Department/Edit.cshtml
@using Pear.Web.Core
@inherits PearRazorPage<object>
@{ Layout = "~/Views/Shared/_Layout.cshtml"; }
@{ ViewData["Title"] = "部门编辑";}
@section header
{

}
<form class="layui-form" action=""  lay-filter="department-edit">
    <div class="mainBox">
        <div class="main-container">
            <div class="main-container">

                <div class="layui-form-item">
                    <label class="layui-form-label">上级部门</label>
                    <div class="layui-input-block">
                        <ul id="ParentDepartment" class="dtree" data-id="null"></ul>
                    </div>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label">名称</label>
                    <div class="layui-input-block">
                        <input type="text" name="name" lay-verify="name" autocomplete="off" placeholder="请输入名称" class="layui-input" />
                    </div>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label">图标</label>
                    <div class="layui-input-block">
                        <input type="text"  name="icon" id="icon" lay-verify="icon" autocomplete="off" placeholder="请输入图标" class="layui-input" />
                    </div>
                </div>


                <div class="layui-form-item">
                    <label class="layui-form-label">电话号码</label>
                    <div class="layui-input-block">
                        <input type="text" name="telephone" autocomplete="off" placeholder="请输入电话号码" class="layui-input" />
                    </div>
                </div>

                <div class="layui-form-item">
                    <label class="layui-form-label">传真号码</label>
                    <div class="layui-input-block">
                        <input type="text" name="fax" lay-verify="authorize" autocomplete="off" placeholder="请输入传真号码" class="layui-input" />
                    </div>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label">邮箱</label>
                    <div class="layui-input-block">
                        <input type="text" name="email" lay-verify="email" autocomplete="off" placeholder="请输入邮箱" class="layui-input" />
                    </div>
                </div>

                <div class="layui-form-item">
                    <label class="layui-form-label">显示排序</label>
                    <div class="layui-input-block">
                        <input type="text" name="sequence" lay-verify="sequence" autocomplete="off" placeholder="请输入排序号码" class="layui-input">
                    </div>
                </div>

                <div class="layui-form-item">
                    <label class="layui-form-label">状态</label>
                    <div class="layui-input-block">
                        <input type="checkbox" name="enabled" value="true" lay-skin="switch" lay-text="启用|禁用" lay-filter="enabled" checked />
                    </div>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label">备注</label>
                    <div class="layui-input-block">
                        <textarea type="text" name="remark" lay-verify="remark" autocomplete="off" placeholder="请输入备注" class="layui-input layui-textarea"></textarea>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="bottom">
        <div class="button-container">
            <button type="submit" class="layui-btn layui-btn-normal layui-btn-sm" lay-submit="" lay-filter="department-save">
                <i class="layui-icon layui-icon-ok"></i>
                提交
            </button>
            <button type="reset" class="layui-btn layui-btn-primary layui-btn-sm">
                <i class="layui-icon layui-icon-refresh"></i>
                重置
            </button>
        </div>
    </div>
</form>
@section footer
{
    <script>
        layui.use(['form', 'jquery', 'http', 'popup', 'dtree','iconPicker'], function () {
            let form = layui.form;
            let $ = layui.jquery;
            let http = layui.http;
            let popup = layui.popup;
            let dtree = layui.dtree;
            let iconPicker = layui.iconPicker;




            var init_select = function (selectInitVal) {
                var tree = dtree.renderSelect({
                    elem: "#ParentDepartment",
                    initLevel: 4,
                    method: 'get',
                    url: "/api/department/all",
                    dataStyle: "layuiStyle",
                    dataFormat: "list",
                    line: true,
                    selectInitVal: `${selectInitVal}`,
                    response: {
                        statusName: "statusCode", //返回标识（必填）
                        statusCode: 200, //返回码（必填）
                        title: "name",
                    }
                });
            }

            iconPicker.render({
                elem: '#icon',
                type: 'fontClass',
                page: false
            });

            http.get('/api/department/profile/@GetValue("id","0")').then((result) => {
                form.val("department-edit", result.data);
                init_select(result.data.parentId);
                iconPicker.checkIcon('icon', result.data.icon);
            });


            form.on('submit(department-save)', function (data) {


                data.field.parentId = data.field.ParentDepartment_select_nodeId || null;

                if (data.field.enabled == "true") {
                    data.field.enabled = true;
                } else {
                    data.field.enabled = false;
                }

                http.post('/api/department/@GetValue("id","0")/modify', JSON.stringify(data.field)).then((result) => {
                    if (result.succeeded) {
                        popup.success("保存成功", function () {
                            parent.layer.close(parent.layer.getFrameIndex(window.name));//关闭当前页
                            parent.refresh();
                        });
                    } else {
                        popup.failure("保存失败");
                    }
                });
                return false;
            });
        })
    </script>
}

src/Pear.Web.Entry/Areas/Admin/Views/Department/Index.cshtml
@using Pear.Web.Core
@inherits PearRazorPage<object>
@{ Layout = "~/Views/Shared/_Layout.cshtml"; }
@{ ViewData["Title"] = "部门管理";}
@section header
{

}
<div class="layui-card">
    <div class="layui-card-body">
        <form class="layui-form" action="">
            <div class="layui-form-item">
                <label class="layui-form-label">部门名称</label>
                <div class="layui-input-inline">
                    <input type="text" name="Keyword" placeholder="" class="layui-input">
                </div>
                <button class="pear-btn pear-btn-md pear-btn-primary" lay-submit lay-filter="department-query">
                    <i class="layui-icon layui-icon-search"></i>
                    查询
                </button>
                <button type="reset" class="pear-btn pear-btn-md" lay-submit lay-filter="department-reset">
                    <i class="layui-icon layui-icon-refresh"></i>
                    重置
                </button>
            </div>
        </form>
    </div>
</div>
<div class="layui-card">
    <div class="layui-card-body">
        <table id="department-table" lay-filter="department-table"></table>
    </div>
</div>
@section footer
{

    <script type="text/html" id="department-toolbar">
        <button class="pear-btn pear-btn-primary pear-btn-md" lay-event="add">
            <i class="layui-icon layui-icon-add-1"></i>
            新增
        </button>
        <button class="pear-btn pear-btn-danger pear-btn-md" lay-event="batchRemove">
            <i class="layui-icon layui-icon-delete"></i>
            删除
        </button>
        <button class="pear-btn pear-btn-success pear-btn-md" lay-event="expandAll">
            <i class="layui-icon layui-icon-spread-left"></i>
            展开
        </button>
        <button class="pear-btn pear-btn-success pear-btn-md" lay-event="foldAll">
            <i class="layui-icon layui-icon-shrink-right"></i>
            折叠
        </button>
    </script>

    <script type="text/html" id="department-bar">
        <button class="pear-btn pear-btn-primary pear-btn-sm" lay-event="edit"><i class="layui-icon layui-icon-edit"></i></button>
        <button class="pear-btn pear-btn-danger pear-btn-sm" lay-event="remove"><i class="layui-icon layui-icon-delete"></i></button>
    </script>

    <script type="text/html" id="department-enabled">
        <input type="checkbox" name="enabled" value="{{d.id}}" lay-skin="switch" lay-text="启用|禁用" lay-filter="department-enabled" {{ d.enabled  ? 'checked' : '' }} />
    </script>

    <script type="text/html" id="icon">
        <i class="layui-icon {{d.icon}}"></i>
    </script>

    <script>
        layui.use(['form', 'jquery', 'treetable','http'], function () {
            let form = layui.form;
            let $ = layui.jquery;
            let treetable = layui.treetable;
            let http = layui.http;
       
            var insTable = treetable.render({
                elem: '#department-table',
                url: '/api/department/all',
                method: 'get',
                toolbar: '#department-toolbar',
                height: 'full-200',
                tree: {
                    iconIndex: 1,
                    isPidData: true,
                    idName: 'id',
                    pidName: 'parentId',
                    arrowType: 'arrow2',
                    getIcon: ''
                },
                defaultToolbar: [{
                    layEvent: 'refresh', icon: 'layui-icon-refresh'
                },'filter', 'print', 'exports'],
                cols: [
                    [
                        { type: 'checkbox' },
                        { field: 'name', minWidth: 200, title: '名称' },
                        { field: 'icon', title: '图标', templet: '#icon' },
                        { field: 'email', title: '邮箱' },
                        { field: 'telephone', title: '电话' },
                        { field: 'enabled', title: '是否可用', templet: '#department-enabled' },
                        { title: '操作', templet: '#department-bar', width: 150, align: 'center' }
                    ]
                ]
            });
 
            treetable.on('tool(department-table)', function (obj) {
                if (obj.event === 'remove') {
                    window.remove(obj);
                } else if (obj.event === 'edit') {
                    window.edit(obj);
                }
            })

            treetable.on('toolbar(department-table)', function (obj) {
                if (obj.event === 'add') {
                    window.add();
                } else if (obj.event === 'refresh') {
                    window.refresh();
                } else if (obj.event === 'batchRemove') {
                    window.batchRemove(obj);
                } else if (obj.event === 'expandAll') {
                    insTable.expandAll();
                } else if (obj.event === 'foldAll') {
                    insTable.foldAll();
                }
            });

            form.on('submit(department-query)', function (data) {
                insTable.filterData(data.field.Keyword)
                return false;
            });

            form.on('submit(department-reset)', function (data) {
                insTable.clearFilter()
                return false;
            });

            window.add = function () {
                layer.open({
                    type: 2,
                    title: '新增',
                    shade: 0.1,
                    area: ['450px', '500px'],
                    content: '@Html.Raw(@Url.Action("Add", "Department", new { area = "Admin" }))'
                });
            }

            window.edit = function (obj) {
                layer.open({
                    type: 2,
                    title: '修改',
                    shade: 0.1,
                    area: ['450px', '500px'],
                    content: '@Html.Raw(@Url.Action("Edit", "Department", new { area = "Admin" }))?id=' + obj.data['id']
                });
            }

            window.remove = function (obj) {
                layer.confirm('确定要删除该权限', { icon: 3, title: '提示' }, function (index) {
                    layer.close(index);
                    let loading = layer.load();

                    http.delete("/api/department/" + obj.data['id']).then((result) => {
                        layer.close(loading);
                        if (result.succeeded) {
                            layer.msg("删除成功", { icon: 1, time: 1000 }, function () {
                                window.refresh();
                            });
                        } else {
                            layer.msg("删除失败", { icon: 2, time: 1000 });
                        }
                    });
                });
            }

            window.refresh = function (param) {
                insTable.refresh();
            }

        })
    </script>
}

src/Pear.Web.Entry/Areas/Admin/Views/Department/_Index.cshtml
@using Pear.Web.Core
@inherits PearRazorPage<object>
@{ Layout = "~/Views/Shared/_Layout.cshtml"; }
@{ ViewData["Title"] = "部门管理";}
@section header
{

}
<div class="layui-card">
    <div class="layui-card-body">
        <form class="layui-form" action="">
            <div class="layui-form-item">
                <div class="layui-form-item layui-inline">
                    <label class="layui-form-label">用户名</label>
                    <div class="layui-input-inline">
                        <input type="text" name="realName" placeholder="" class="layui-input">
                    </div>
                </div>
                <div class="layui-form-item layui-inline">
                    <label class="layui-form-label">性别</label>
                    <div class="layui-input-inline">
                        <input type="text" name="realName" placeholder="" class="layui-input">
                    </div>
                </div>
                <div class="layui-form-item layui-inline">
                    <label class="layui-form-label">邮箱</label>
                    <div class="layui-input-inline">
                        <input type="text" name="realName" placeholder="" class="layui-input">
                    </div>
                </div>
                <div class="layui-form-item layui-inline">
                    <button class="pear-btn pear-btn-md pear-btn-primary" lay-submit lay-filter="user-query">
                        <i class="layui-icon layui-icon-search"></i>
                        查询
                    </button>
                    <button type="reset" class="pear-btn pear-btn-md">
                        <i class="layui-icon layui-icon-refresh"></i>
                        重置
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="layui-row layui-col-space15">
    <div class="layui-col-md3">
        <div class="layui-card">
            <div class="layui-card-body">
                <div id="organizationTreeContent" style="overflow: auto">
                    <ul id="organizationTree" class="dtree organizationTree" data-id="9527"></ul>
                </div>
            </div>
        </div>
    </div>
    <div class="layui-col-md9">
        <div class="layui-card">
            <div class="layui-card-body">
                <table id="organization-table" lay-filter="organization-table"></table>
            </div>
        </div>
    </div>
</div>
@section footer
{

    <script type="text/html" id="organization-toolbar">
        <button class="pear-btn pear-btn-primary pear-btn-md" lay-event="add">
            <i class="layui-icon layui-icon-add-1"></i>
            新增
        </button>
        <button class="pear-btn pear-btn-danger pear-btn-md" lay-event="batchRemove">
            <i class="layui-icon layui-icon-delete"></i>
            删除
        </button>
    </script>

    <script type="text/html" id="organization-bar">
        <button class="pear-btn pear-btn-primary pear-btn-sm" lay-event="edit">
            <i class="layui-icon layui-icon-edit"></i>
        </button>
        <button class="pear-btn pear-btn-danger pear-btn-sm" lay-event="remove">
            <i class="layui-icon layui-icon-delete"></i>
        </button>
    </script>

    <script>
        layui.use(['table', 'form', 'jquery', 'dtree'], function () {
            let table = layui.table;
            let form = layui.form;
            let $ = layui.jquery;
            let dtree = layui.dtree;

            let MODULE_PATH = "operate/";

            let cols = [
                [{
                    type: 'checkbox'
                },
                {
                    title: '名称',
                    field: 'name',
                    align: 'center'
                },
                {
                    title: '人数',
                    field: 'userCount',
                    align: 'center'
                },
                {
                    title: '位置',
                    field: 'location',
                    align: 'center'
                },
                {
                    title: '负责人',
                    field: 'leader',
                    align: 'center'
                },
                {
                    title: '操作',
                    toolbar: '#organization-bar',
                    align: 'center',
                    width: 130
                }
                ]
            ]

            var DTree = dtree.render({
                elem: "#organizationTree",
                //data: data,
                initLevel: "2", //默认展开层级为1
                line: true, // 有线树
                ficon: ["1", "-1"], // 设定一级图标样式。0表示方形加减图标，8表示小圆点图标
                icon: ["0", "2"], // 设定二级图标样式。0表示文件夹图标，5表示叶子图标
                method: 'get',
                url: "/admin/data/organizationtree.json"
            });

            table.render({
                elem: '#organization-table',
                url: '/admin/data/organization.json',
                height: 'full-150',
                page: true,
                cols: cols,
                skin: 'line',
                toolbar: '#organization-toolbar',
                defaultToolbar: [{
                    layEvent: 'refresh',
                    icon: 'layui-icon-refresh',
                }, 'filter', 'print', 'exports']
            });

            // 绑定节点点击事件
            dtree.on("node(organizationTree)", function (obj) {
                if (!obj.param.leaf) {
                    var $div = obj.dom;
                    DTree.clickSpread($div); //调用内置函数展开节点
                } else {
                    layer.msg("叶子节点就不展开了,刷新右侧列表");
                    table.reload("organization-table");
                }
            });

            table.on('tool(organization-table)', function (obj) {
                if (obj.event === 'remove') {
                    window.remove(obj);
                } else if (obj.event === 'edit') {
                    window.edit(obj);
                }
            });

            table.on('toolbar(organization-table)', function (obj) {
                if (obj.event === 'add') {
                    window.add();
                } else if (obj.event === 'refresh') {
                    window.refresh();
                } else if (obj.event === 'batchRemove') {
                    window.batchRemove(obj);
                }
            });

            form.on('submit(organization-query)', function (data) {
                table.reload('organization-table', {
                    where: data.field
                })
                return false;
            });

            window.add = function () {
                layer.open({
                    type: 2,
                    title: '新增',
                    shade: 0.1,
                    area: ['500px', '400px'],
                    content: MODULE_PATH + 'add.html'
                });
            }

            window.edit = function (obj) {
                layer.open({
                    type: 2,
                    title: '修改',
                    shade: 0.1,
                    area: ['500px', '400px'],
                    content: MODULE_PATH + 'edit.html'
                });
            }

            window.remove = function (obj) {
                layer.confirm('确定要删除该用户', {
                    icon: 3,
                    title: '提示'
                }, function (index) {
                    layer.close(index);
                    let loading = layer.load();
                    $.ajax({
                        url: MODULE_PATH + "remove/" + obj.data['organizationId'],
                        dataType: 'json',
                        type: 'delete',
                        success: function (result) {
                            layer.close(loading);
                            if (result.success) {
                                layer.msg(result.msg, {
                                    icon: 1,
                                    time: 1000
                                }, function () {
                                    obj.del();
                                });
                            } else {
                                layer.msg(result.msg, {
                                    icon: 2,
                                    time: 1000
                                });
                            }
                        }
                    })
                });
            }

            window.batchRemove = function (obj) {
                let data = table.checkStatus(obj.config.id).data;
                if (data.length === 0) {
                    layer.msg("未选中数据", {
                        icon: 3,
                        time: 1000
                    });
                    return false;
                }
                let ids = "";
                for (let i = 0; i < data.length; i++) {
                    ids += data[i].organizationId + ",";
                }
                ids = ids.substr(0, ids.length - 1);
                layer.confirm('确定要删除这些用户', {
                    icon: 3,
                    title: '提示'
                }, function (index) {
                    layer.close(index);
                    let loading = layer.load();
                    $.ajax({
                        url: MODULE_PATH + "batchRemove/" + ids,
                        dataType: 'json',
                        type: 'delete',
                        success: function (result) {
                            layer.close(loading);
                            if (result.success) {
                                layer.msg(result.msg, {
                                    icon: 1,
                                    time: 1000
                                }, function () {
                                    table.reload('organization-table');
                                });
                            } else {
                                layer.msg(result.msg, {
                                    icon: 2,
                                    time: 1000
                                });
                            }
                        }
                    })
                });
            }

            window.refresh = function (param) {
                table.reload('organization-table');
            }
        })
    </script>
}