src/Pear.Web.Entry/Areas/Admin/Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;


namespace Pear.Web.Entry.Areas.Admin.Controllers
{

    /// <summary>
    /// 角色-后台控制器
    /// </summary>
    [Area("Admin")]
    [Route("Admin/[controller]/[action]")]
    [AppAuthorize]
    public class RoleController : Controller
    {
        /// <summary>
        /// 角色管理-主视图
        /// </summary>
        /// <returns></returns>
        [SecurityDefine("admin.system.role:view")]
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 角色新增-视图
        /// </summary>
        /// <returns></returns>
        [SecurityDefine("admin.system.role:add")]
        public IActionResult Add()
        {
            return View();
        }

        /// <summary>
        /// 角色编辑-视图
        /// </summary>
        /// <returns></returns>
        [SecurityDefine("admin.system.role:edit")]
        public IActionResult Edit()
        {
            return View();
        }


        /// <summary>
        /// 为角色分配权限菜单-视图
        /// </summary>
        /// <returns></returns>
        [SecurityDefine("admin.system.role:give")]
        public IActionResult Give()
        {
            return View();
        }
    }
}

src/Pear.Web.Entry/Areas/Admin/Views/Role/Add.cshtml
@using Pear.Web.Core
@inherits PearRazorPage<object>
@{ Layout = "~/Views/Shared/_Layout.cshtml"; }
@{ ViewData["Title"] = "角色新增";}
@section header
{

}
<form class="layui-form" action="">
    <div class="mainBox">
        <div class="main-container">
            <div class="main-container">
                <div class="layui-form-item">
                    <label class="layui-form-label">账户</label>
                    <div class="layui-input-block">
                        <input type="text" name="name" lay-verify="name" autocomplete="off" placeholder="请输入账户" class="layui-input">
                    </div>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label">备注</label>
                    <div class="layui-input-block">
                        <textarea type="text" name="remark" lay-verify="remark" autocomplete="off" placeholder="请输入标题" class="layui-input layui-textarea"></textarea>
                    </div>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label">状态</label>
                    <div class="layui-input-block">
                        <input type="checkbox" name="enabled" value="true" lay-skin="switch" lay-text="启用|禁用" lay-filter="enabled" checked />
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="bottom">
        <div class="button-container">
            <button type="submit" class="layui-btn layui-btn-normal layui-btn-sm" lay-submit="" lay-filter="user-save">
                <i class="layui-icon layui-icon-ok"></i>
                提交
            </button>
            <button type="reset" class="layui-btn layui-btn-primary layui-btn-sm">
                <i class="layui-icon layui-icon-refresh"></i>
                重置
            </button>
        </div>
    </div>
</form>
@section footer
{
    <script>
        layui.use(['form', 'jquery', 'http', 'popup'], function () {
            let form = layui.form;
            let $ = layui.jquery;
            let http = layui.http;
            let popup = layui.popup;

            

            form.on('submit(user-save)', function (data) {
                if (data.field.enabled == "true") {
                    data.field.enabled = true;
                } else {
                    data.field.enabled = false;
                }
                http.post('/api/role/add', JSON.stringify(data.field)).then((result) => {
                    if (result.succeeded) {
                        popup.success("保存成功", function () {
                            parent.layer.close(parent.layer.getFrameIndex(window.name));//关闭当前页
                            parent.layui.table.reload("role-table");
                        });
                    } else {
                        popup.failure("保存失败");
                    }
                });
                return false;
            });
        })
    </script>
}

src/Pear.Web.Entry/Areas/Admin/Views/Role/Edit.cshtml
@using Pear.Web.Core
@inherits PearRazorPage<object>
@{ Layout = "~/Views/Shared/_Layout.cshtml"; }
@{ ViewData["Title"] = "角色修改";}
@section header
{

}
<form class="layui-form" action="" lay-filter="role-edit">
    <div class="mainBox">
        <div class="main-container">
            <div class="main-container">
                <div class="layui-form-item">
                    <label class="layui-form-label">账户</label>
                    <div class="layui-input-block">
                        <input type="text" name="name" lay-verify="name" autocomplete="off" placeholder="请输入角色名称" class="layui-input">
                    </div>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label">备注</label>
                    <div class="layui-input-block">
                        <textarea type="text" name="remark" lay-verify="remark" autocomplete="off" placeholder="请输入备注" class="layui-input layui-textarea"></textarea>
                    </div>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label">状态</label>
                    <div class="layui-input-block">
                        <input type="checkbox" name="enabled" value="true" lay-skin="switch" lay-text="启用|禁用" lay-filter="enabled" checked />
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="bottom">
        <div class="button-container">
            <button type="submit" class="layui-btn layui-btn-normal layui-btn-sm" lay-submit="" lay-filter="role-save">
                <i class="layui-icon layui-icon-ok"></i>
                提交
            </button>
            <button type="reset" class="layui-btn layui-btn-primary layui-btn-sm">
                <i class="layui-icon layui-icon-refresh"></i>
                重置
            </button>
        </div>
    </div>
</form>
@section footer
{

    <script>
        layui.use(['form', 'jquery', 'http', 'popup'], function () {
            let form = layui.form;
            let $ = layui.jquery;
            let http = layui.http;
            let popup = layui.popup;



            http.get('/api/role/profile/@GetValue("id","0")').then((result) => {
                form.val("role-edit", result.data);
            });

            form.on('submit(role-save)', function (data) {

                if (data.field.enabled == "true") {
                    data.field.enabled = true;
                } else {
                    data.field.enabled = false;
                }

                http.post('/api/role/@GetValue("id","0")/modify', JSON.stringify(data.field)).then((result) => {
                    if (result.succeeded) {
                        popup.success("修改成功", function () {
                            parent.layer.close(parent.layer.getFrameIndex(window.name));//关闭当前页
                            parent.layui.table.reload("role-table");
                        });
                    } else {
                        popup.failure("修改失败");
                    }
                });
                return false;
            });
        })
    </script>
}

src/Pear.Web.Entry/Areas/Admin/Views/Role/Give.cshtml
@using Pear.Web.Core
@inherits PearRazorPage<object>
@{ Layout = "~/Views/Shared/_Layout.cshtml"; }
@{ ViewData["Title"] = "角色分配";}
@section header
{

}
<form class="layui-form" action="" lay-filter="user-edit">
    <div class="mainBox">
        <div class="main-container">

            <ul id="dtree" class="dtree" data-id="null" lay-filter="dtree"></ul>


        </div>
    </div>
    <div class="bottom">
        <div class="button-container">
            <button type="submit" class="layui-btn layui-btn-normal layui-btn-sm" lay-submit="" lay-filter="role-give">
                <i class="layui-icon layui-icon-ok"></i>
                提交
            </button>
            <button type="reset" class="layui-btn layui-btn-primary layui-btn-sm">
                <i class="layui-icon layui-icon-refresh"></i>
                重置
            </button>
        </div>
    </div>
</form>
@section footer
{
    <script>
        layui.use(['form', 'jquery', 'http', 'popup','dtree'], function () {
            let form = layui.form;
            let $ = layui.jquery;
            let http = layui.http;
            let popup = layui.popup;
            let dtree = layui.dtree;





            var tree = dtree.render({
                elem: "#dtree",
                method: 'get',
                url: "/api/security/all",
                dataStyle: "layuiStyle",
                dataFormat: "list",
                checkbar: true,
                response: {
                    statusName: "statusCode",
                    statusCode: 200,
                    title: "name",
                    checkArr: "checkArr"
                },
                done: function (res, dom, first) {
                    if (first) {
                        http.get('/api/role/@GetValue("id","0")/securities').then((result) => {
                            if (result.succeeded) {
                                let chooses = [];
                                $.each(result.data, (i, item) => {
                                    chooses[i] = item.id;
                                });
                                dtree.chooseDataInit("dtree", chooses);
                            }
                        });
                    }
                }
            });



            form.on('submit(role-give)', function (data) {
                var params = dtree.getCheckbarNodesParam("dtree");

                let securitieIds = "";
                $.each(params,function (i,item) {
                    securitieIds += item.nodeId + ",";
                });
                securitieIds = securitieIds.substr(0, securitieIds.length - 1);
                var saveIds = new Array();
                saveIds = securitieIds.split(",");
                http.post('/api/security/give/@GetValue("id","0")', JSON.stringify(saveIds)).then((result) => {
                    if (result.succeeded) {
                        popup.success("修改成功", function () {
                            parent.layer.close(parent.layer.getFrameIndex(window.name));//关闭当前页
                            parent.layui.table.reload("role-table");
                        });
                    } else {
                        popup.failure("修改失败");
                    }
                });
                return false;
            });
        })
    </script>
}

src/Pear.Web.Entry/Areas/Admin/Views/Role/Index.cshtml
@using Pear.Web.Core
@inherits PearRazorPage<object>
@{ Layout = "~/Views/Shared/_Layout.cshtml"; }
@{ ViewData["Title"] = "角色管理";}
@section header
{
    <style>
        .layui-card-body .layui-form-item {
            margin-bottom: 0px;
        }
    </style>
}

<div class="layui-card">
    <div class="layui-card-body">
        <form class="layui-form" action="">
            <div class="layui-form-item">
                <div class="layui-form-item layui-inline">
                    <label class="layui-form-label">角色名</label>
                    <div class="layui-input-inline">
                        <input type="text" name="name" placeholder="" class="layui-input">
                    </div>
                </div>
                <div class="layui-form-item layui-inline">
                    <button class="pear-btn pear-btn-md pear-btn-primary" lay-submit lay-filter="user-query">
                        <i class="layui-icon layui-icon-search"></i>
                        查询
                    </button>
                    <button type="reset" class="pear-btn pear-btn-md">
                        <i class="layui-icon layui-icon-refresh"></i>
                        重置
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="layui-card">
    <div class="layui-card-body">
        <table id="role-table" lay-filter="role-table"></table>
    </div>
</div>

@section footer
{

    <script type="text/html" id="role-toolbar">
        <button class="pear-btn pear-btn-primary pear-btn-md" lay-event="add">
            <i class="layui-icon layui-icon-add-1"></i>
            新增
        </button>
        <button class="pear-btn pear-btn-danger pear-btn-md" lay-event="batchRemove">
            <i class="layui-icon layui-icon-delete"></i>
            删除
        </button>
    </script>

    <script type="text/html" id="role-bar">
        <button class="pear-btn pear-btn-primary pear-btn-sm" lay-event="edit"><i class="layui-icon layui-icon-edit"></i></button>
        <button class="pear-btn pear-btn-warming pear-btn-sm" lay-event="give"><i class="layui-icon layui-icon-vercode"></i></button>
        <button class="pear-btn pear-btn-danger pear-btn-sm" lay-event="remove"><i class="layui-icon layui-icon-delete"></i></button>
    </script>

    <script type="text/html" id="role-enabled">
        <input type="checkbox" name="enabled" value="{{d.id}}" lay-skin="switch" lay-text="启用|禁用" lay-filter="role-enabled"  {{d.enabled ? 'checked' : '' }} />
    </script>

    <script>
        layui.use(['table', 'form', 'jquery', 'popup', 'common','http'], function () {
            let table = layui.table;
            let form = layui.form;
            let $ = layui.jquery;
            let common = layui.common;
            let popup = layui.popup;
            let http = layui.http;


            let cols =
                [[
                    { type: 'checkbox' },
                    { title: '编号', field: 'id', align: 'center', width: 100 },
                    { title: '名称', field: 'name', align: 'center' },
                    { title: '描述', field: 'remark', align: 'center' },
                    { title: '是否可用', field: 'enabled', align: 'center', templet: '#role-enabled' },
                    { title: '操作', toolbar: '#role-bar', align: 'center', width: 195 }
                ]]

            table.render({
                elem: '#role-table',
                url:  '/api/role/list',
                page: true,
                cols: cols,
                skin: 'line',
                toolbar: '#role-toolbar',
                defaultToolbar: [{
                    layEvent: 'refresh', icon: 'layui-icon-refresh'
                },
                    'exports',
                    'filter',
                    'print'
                ],
                request: {
                    pageName: 'PageIndex',
                    limitName: 'PageSize'
                },
                parseData: function (res) {
                    return {
                        "count": res.data.totalCount,
                        'statusCode': res.statusCode,
                        'data': res.data.items
                    };
                },
                response: {
                    statusName: 'statusCode',
                    statusCode: 200
                }
            });

            table.on('tool(role-table)', function (obj) {
                if (obj.event === 'remove') {
                    window.remove(obj);
                } else if (obj.event === 'edit') {
                    window.edit(obj);
                } else if (obj.event === 'give') {
                    window.give(obj);
                }
            });

            table.on('toolbar(role-table)', function (obj) {
                if (obj.event === 'add') {
                    window.add();
                } else if (obj.event === 'refresh') {
                    window.refresh();
                } else if (obj.event === 'batchRemove') {
                    window.batchRemove(obj);
                }
            });

            form.on('submit(role-query)', function (data) {
                table.reload('role-table', { where: data.field })
                return false;
            });

            // 后续会提供单独接口
            form.on('switch(role-enabled)', function (obj) {
                http.post('/api/role/' + this.value + '/change-enabled', JSON.stringify({ "enabled": obj.elem.checked }))
                    .then(function (result) {
                        if (result.succeeded) {
                            popup.success("操作成功");
                        } else {
                            popup.failure("操作失败");
                        }
                    });
            });

            window.add = function () {
                layer.open({
                    type: 2,
                    title: '新增角色',
                    shade: 0.1,
                    area: ['500px', '400px'],
                    content: '@Html.Raw(@Url.Action("Add", "Role", new { area = "Admin" }))'
                });
            }

            window.give = function (obj) {
                layer.open({
                    type: 2,
                    title: '分配',
                    shade: 0.1,
                    area: ['400px', '500px'],
                    content: '@Html.Raw(@Url.Action("Give", "Role", new { area = "Admin" }))?id=' + obj.data['id']
                });
            }

            window.power = function (obj) {
                layer.open({
                    type: 2,
                    title: '授权',
                    shade: 0.1,
                    area: ['320px', '400px'],
                    content: '@Html.Raw(@Url.Action("Edit", "Role", new { area = "Admin" }))'
                });
            }

            window.edit = function (obj) {
                layer.open({
                    type: 2,
                    title: '修改',
                    shade: 0.1,
                    area: ['500px', '400px'],
                    content: '@Html.Raw(@Url.Action("Edit", "Role", new { area = "Admin" }))?id=' + obj.data['id']
                });
            }

            window.remove = function (obj) {
                layer.confirm('确定要删除该角色', {
                    icon: 3,
                    title: '提示'
                }, function (index) {
                    layer.close(index);
                    let roleIds = new Array();
                    roleIds.push(obj.data['id']);
                    let loading = layer.load();
                    http.delete("/api/role", JSON.stringify(roleIds)).then((result) => {
                        layer.close(loading);
                        if (result.succeeded) {
                            popup.success("删除成功", function () {
                                window.refresh();
                            });
                        } else {
                            popup.failure("删除失败");
                        }
                    });
                });
            }

            window.batchRemove = function (obj) {
                var checkIds = common.checkField(obj, 'id');
                if (checkIds === "") {
                    layer.msg("未选中数据", { icon: 3, time: 1000 });
                    return false;
                }
                layer.confirm('确定要删除选中角色', { icon: 3, title: '提示' }, function (index) {
                    layer.close(index);
                    var roleIds = new Array(); //定义一数组
                    roleIds = checkIds.split(","); //字符分割
                    let loading = layer.load();

                    http.delete("/api/role", JSON.stringify(roleIds)).then((result) => {
                        layer.close(loading);
                        if (result.succeeded) {
                            popup.success("删除成功", function () {
                                table.reload("role-table");
                            });
                        } else {
                            popup.failure("删除失败");
                        }
                    });
                });
            }

            window.refresh = function () {
                table.reload('role-table');
            }
        })
    </script>
}